"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def problem2(max):
    s = [1,2]
    i = even = 2
    while i <= max:
        i += s[len(s)-2]
        s.append(i)
        if i%2 == 0:
            even += i
        print (s)
    return even
        
max = 4000000
print(problem2(max))

#Answer is 4613732